### ISSUE TITLE
训练咨询

### ISSUE THREAD

**Issue by IeohMingChan** [ChunjingXiao/DeepSeg#4]
你好，我想问一下06Classification_ClassifyActivity文件夹中的2test_7_parameterEntropy.bat运行后生成的actionTestCsi_entropy_ema反馈文件应该怎么正确使用呢？看起来是使用04Segment_StateInference/1train_4_200_30_3_Mat2npy_Weight_Segm.py中的wtrain参数使用，但我把这个文件放在04Segment_StateInference/data中并更名为actionTrainCsi_entropy_ema再运行04Segment_StateInference/1train_4_200_30_3_Mat2npy_Weight_Segm.py时会报出数组越界错误，万分感谢！
 File "1train_4_200_30_3_Mat2npy_Weight_Segm.py", line 172, in main
    sWeight= sWeight[inds]
IndexError: index 2831 is out of bounds for axis 0 with size 250

**Comment by ChunjingXiao** [comment]
这个错误可能是因为行数不足造成的，actionTrainCsi_entropy_ema文件中的行数应该与训练集中动作的样本数一样。
根据出错提示，你生的actionTrainCsi_entropy_ema只有250行，而训练样本有2831个。
要用训练数据生成actionTrainCsi_entropy_ema，其行数要与训练样本一致。

**Comment by IeohMingChan** [comment]
> 这个错误可能是因为行数不足造成的，actionTrainCsi_entropy_ema文件中的行数应该与训练集中动作的样本数一样。 根据出错提示，你生的actionTrainCsi_entropy_ema只有250行，而训练样本有2831个。 要用训练数据生成actionTrainCsi_entropy_ema，其行数要与训练样本一致。

你好，我根据你的指示重新运行2test_7_parameterEntropy.bat文件并使用actionBaseTrain.mat训练集作为输入数据，但由于该训练集行数只有1250行，因此行数仍然不足。然后我使用调试模式定位了一下04Segment_StateInference/1train_4_200_30_3_Mat2npy_Weight_Segm.py中的报错位置，发现sWeight= sWeight[inds]语句中的inds为(5000,)的ndarray矩阵，最大值为4999，最小值为0，结合报错前的输出信息：
(5000, 120, 30, 3)
(5000,)
(1000, 120, 30, 3)
(1000,)
trainx.shape     :: (5000, 120, 30, 3)
trainy.shape     :: (5000,)
testx.shape      :: (1000, 120, 30, 3)
testy.shape      :: (1000,)
python-BaseException
sWeight.shape    :: (1250, 7)
Traceback (most recent call last):
  File "/home/clm/anaconda3/envs/python3.6/lib/python3.6/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/clm/anaconda3/envs/python3.6/lib/python3.6/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/home/clm/DeepSeg/04Segment_StateInference/1train_4_200_30_3_Mat2npy_Weight_Segm.py", line 172, in main
    sWeight= sWeight[inds]
IndexError: index 2831 is out of bounds for axis 0 with size 1250
报错位置附近的代码如下，位于04Segment_StateInference/1train_4_200_30_3_Mat2npy_Weight_Segm.py的main()函数中：
(trainx,trainy,testx,testy) = loadData(args.dataDir, args.trainCsi,args.trainLab,args.testCsi,args.testLab)
    rng_data = np.random.RandomState(rng.randint(0, 2**10))  # seed shuffling    
    inds = rng_data.permutation(trainx.shape[0])   #-----------------xiao--------shuffling data-------------
    trainx = trainx[inds]
    trainy = trainy[inds]
    
    if(args.wtrain):         #--------------------------add for sample Weight-------20191214------xiao------------   
        sWeight = np.loadtxt(args.dataDir + '/' +'actionBaseTrainCsi_entropy_ema')
        print('sWeight.shape    ::', sWeight.shape) 
        sWeight= sWeight[inds]
    inds = rng_data.permutation(testx.shape[0])
    testx = testx[inds]
    testy = testy[inds]
所以是否意味着我需要5000个训练数据生成actionTrainCsi_entropy_ema才能提供足够的行数？再次感谢你的解答

**Comment by ChunjingXiao** [comment]
actionTrainCsi_entropy_ema是要5000行才够。

**Comment by IeohMingChan** [comment]
> actionTrainCsi_entropy_ema是要5000行才够。

好的，谢谢肖教授耐心解答
